script: bundle exec rspec
gemfile:
  - gemfiles/rails_3.2.13.gemfile
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.beta2.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby
matrix:
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/rails_3.2.13.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails_3.2.13.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.2.0.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_4.2.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.0.0.beta2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.0.beta2.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5.0.0.beta2.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_5.0.0.beta2.gemfile
before_install:
  - gem update bundler