script: bundle exec rspec
gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
rvm:
  - 2.3.0
before_install:
  - gem update bundler
